import { CrudConfig } from "@/components/admin-crud-page";

export const crudConfigs: Record<string, CrudConfig> = {
  organizations: { table: "organizations", title: "Organizations", description: "Manage collection businesses on the platform.", searchFields: ["name", "legal_name", "contact_email", "phone", "address", "city", "state", "country", "pincode"], columns: ["name", "legal_name", "contact_email", "phone", "city", "state", "country", "pincode", "status", "created_at"], fields: [{ name: "name", label: "Organization Name", required: true }, { name: "legal_name", label: "Legal Name", type: "text" }, { name: "contact_email", label: "Admin login email", type: "text", required: true }, { name: "phone", label: "Admin WhatsApp number", type: "text", required: true }, { name: "address", label: "Address", type: "textarea" }, { name: "city", label: "City", type: "text" }, { name: "state", label: "State", type: "text" }, { name: "country", label: "Country", type: "text" }, { name: "pincode", label: "Pincode", type: "text" }] },
  users: { table: "profiles", title: "Users", description: "Create login users for an organization and manage access roles.", searchFields: ["id", "full_name", "email", "platform_role"], columns: ["full_name", "email", "platform_role", "organization_id", "is_active", "created_at"], fields: [{ name: "full_name", label: "Full name", required: true }, { name: "email", label: "Email", required: true }, { name: "password", label: "Temporary password", required: true }, { name: "phone", label: "Phone" }, { name: "organization_id", label: "Organization", type: "select", required: true }, { name: "platform_role", label: "Role", type: "select", options: ["CLIENT", "MANAGER", "FIELD_EXECUTIVE", "BACKEND"], required: true }, { name: "is_active", label: "Status", type: "checkbox" }] },
  packages: { table: "packages", title: "Packages", description: "Create plans and pricing for organizations.", searchFields: ["name", "billing_period"], columns: ["name", "price", "validity_days", "discount_percentage", "billing_period", "is_active"], fields: [{ name: "name", label: "Name", required: true }, { name: "description", label: "Description", type: "textarea" }, { name: "price", label: "Price (INR)", type: "number", required: true }, { name: "validity_days", label: "Validity (days)", type: "number", required: true }, { name: "discount_percentage", label: "Discount (%)", type: "number" }, { name: "billing_period", label: "Billing period", type: "select", options: ["MONTHLY", "YEARLY"], required: true }, { name: "is_active", label: "Status", type: "checkbox" }] },
  subscriptions: { table: "subscriptions", title: "Subscriptions", description: "Assign active packages to organizations and track plan dates.", searchFields: ["organization_id", "package_id", "status"], fields: [{ name: "organization_id", label: "Organization", type: "select", required: true }, { name: "package_id", label: "Package", type: "select", required: true }, { name: "status", label: "Status", type: "select", options: ["ACTIVE", "PAUSED", "CANCELLED", "EXPIRED"], required: true }, { name: "starts_at", label: "Starts", type: "date", required: true }, { name: "ends_at", label: "Ends", type: "date" }] },
  "loan-types": { table: "loan_types", title: "Loan Types", description: "Configure collection products and their calculation rules.", searchFields: ["name", "description", "collection_frequency", "interest_type"], columns: ["name", "interest_type", "interest_rate", "tenure_days", "collection_frequency", "min_amount", "max_amount", "is_active"], fields: [{ name: "name", label: "Name", required: true }, { name: "description", label: "Description", type: "textarea" }, { name: "interest_type", label: "Interest type", type: "select", options: ["FLAT", "PERCENTAGE"], required: true }, { name: "interest_rate", label: "Interest rate", type: "number", required: true }, { name: "tenure_days", label: "Tenure (days)", type: "number", required: true }, { name: "collection_frequency", label: "Collection frequency", type: "select", options: ["DAILY", "WEEKLY", "MONTHLY"], required: true }, { name: "min_amount", label: "Minimum amount", type: "number", required: true }, { name: "max_amount", label: "Maximum amount", type: "number" }, { name: "is_active", label: "Status", type: "checkbox" }] },
  payments: { table: "payments", title: "Payments", description: "Record and review organization subscription payments.", searchFields: ["organization_id", "status", "reference"], fields: [{ name: "organization_id", label: "Organization", type: "select", required: true }, { name: "amount", label: "Amount (INR)", type: "number", required: true }, { name: "status", label: "Status", type: "select", options: ["PENDING", "PAID", "FAILED", "REFUNDED"], required: true }, { name: "reference", label: "Reference" }, { name: "paid_at", label: "Paid date", type: "date" }] },
};